# MAKEFILE for phn_output.py (Environment: OS:Windows / nmake.exe)
# vim: fileencoding=utf-8
#
# https://github.com/tatt61880/phn_output
# Copyright (C) 2011 - 2020 tatt61880 (たっと)
# Last Modified: 2020/05/12 03:41:23.

PHN_OUTPUT = phn_output
PYTHON30 = python
EXAMPLE = example

all: test

# Test {{{1
test : Pseudotarget
	$(PYTHON30) $(PHN_OUTPUT).test.py --disable_warnings

test3 : Pseudotarget
	$(PYTHON30) $(PHN_OUTPUT).test.py
#}}}1

# Debug {{{1
debug : Pseudotarget
	$(PYTHON30) $(PHN_OUTPUT).test.py --debug --disable_warnings

debug3 : Pseudotarget
	$(PYTHON30) $(PHN_OUTPUT).test.py --debug
#}}}1

# phn {{{1
phn: Pseudotarget
	$(PYTHON30) $(PHN_OUTPUT).py $(EXAMPLE).svg > $(EXAMPLE).phn
# }}}1

# Run {{{1
run: phn
	start $(EXAMPLE).phn
run3: phn3
	start $(EXAMPLE).phn
#}}}1

zip: phn
	$(PYTHON30) zip_this_project.py

Pseudotarget:

.SUFFIXES: .svg

.svg.phn:
	$(PYTHON30) $(PHN_OUTPUT).py $< > $@

help: Pseudotarget
	@echo --- targets ---
	@echo - all   : test
	@echo - test
	@echo - debug
	@echo - zip
	@echo - help
	@echo - run   : phn
	@echo - phn
	@echo - *.phn suffix rule

# vim: shiftwidth=4 tabstop=8 softtabstop=4 fileencoding=utf-8 textwidth=99
